### ISSUE TITLE
Unable to use skia.GrGLFramebufferInfo 

### ISSUE THREAD

**Issue by parsoyaarihant** [kyamagu/skia-python#98]
**Describe the bug**

```python
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    surface = init_surface(width, height)
  File "test.py", line 14, in init_surface
    skia.GrGLFramebufferInfo(0, GL.GL_RGBA8))
AttributeError: module 'skia' has no attribute 'GrGLFramebufferInfo'
```

**To Reproduce**
Run
```python
import skia
import glfw
from OpenGL import GL

width, height = 200, 200

def init_surface(width, height):
    context = skia.GrContext.MakeGL()
    backend_render_target = skia.GrBackendRenderTarget(
        width,
        height,
        0,  # sample count
        0,  # stencil bits
        skia.GrGLFramebufferInfo(0, GL.GL_RGBA8))
    surface = skia.Surface.MakeFromBackendRenderTarget(
        context, backend_render_target, skia.kBottomLeft_GrSurfaceOrigin,
        skia.kRGBA_8888_ColorType, skia.ColorSpace.MakeSRGB())
    assert surface, 'Failed to create a surface'
    return surface

if not glfw.init():
    raise RuntimeError('glfw.init() failed')

glfw.window_hint(glfw.STENCIL_BITS, 0)
glfw.window_hint(glfw.DEPTH_BITS, 0)

window = glfw.create_window(640, 480, 'Demo', None, None)
glfw.make_context_current(window)
glfw.swap_interval(1)

surface = init_surface(width, height)
canvas = surface.getCanvas()

# Loop until the user closes the window
while not glfw.window_should_close(window):
    glfw.wait_events()

    # Render here
    canvas.clear(skia.ColorGREEN)
    surface.flushAndSubmit()

    # Swap front and back buffers
    glfw.swap_buffers(window)

    # Poll for and process events
    glfw.poll_events()

glfw.terminate()
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Python: 3.6
 - skia-python version: 0.0.6

**Comment by kyamagu** [comment]
Are you sure you are using v0.0.6? `GrGLFramebufferInfo` gets binding since v0.0.6
https://github.com/kyamagu/skia-python/commit/83c6e7404111f5b34228c214b179fc62c53272b1

**Comment by parsoyaarihant** [comment]
I was using 0.0.5. Thanks for the help.
